### PR TITLE
Added hideExtract option.

### PR DESCRIPTION
**Pull request by linuxrules94**
I fixed the request. This should work.

### CODE REVIEW

**Comment by LexManos** [comment]
I don't particularly see a reason for this but whatever.

**Comment by linuxrules94** [comment]
Thanks, I though it would be good for mod installers.

**Comment by LexManos** [comment]
Mods dont need installers... they are just 'put me in the folder' Never understood why someone needs a installer for that.

**Comment by linuxrules94** [comment]
Some multiplayer servers have their own mod (pack) installers for clients.

**Pull request merged**
