### PR TITLE
Use gradle 4.9 instead of 4.10

### PR DESCRIPTION
**Pull request by Niko-sk2x**
Gradle 4.10 has a feature where it will clean "old" files from gradle cache after they aren't used by gradle or some short time. This usually results in a broken mod dev environment when it happens, as this is done globally for the whole cache.

### CODE REVIEW

**Comment by liach** [comment]
The wrapper jar needs an actual update. It appears the jar is still for gradle 2.

**Comment by LexManos** [comment]
Could just change the cache directory...
But yes this is a stupid change on gradle's part.

**Comment by Niko-sk2x** [comment]
Changing the gradle cache location only works as long as you never forget to do it and never miss a potential place gradle may be executed from. And only as long as whoever is running gradle actually knows about it. If it was just about me, I wouldn't submit this PR.

**Review by liach — APPROVED** [review]

**Comment by bs2609** [comment]
Can this also use the `bin` distribution instead of `all`, as it's a reasonably smaller download?

**Comment by Niko-sk2x** [comment]
I used all because that's what was used before so I wasn't sure if it was ok to change that.

**Comment by LexManos** [comment]
All is preferred as it's only a few MB more and includes all the javadocs and debugging stuff.
IF there was a way to specify dev/ci wrappers that'd be ideal.

**Pull request merged**
