### PR TITLE
Added install client over cli option

### PR DESCRIPTION
**Pull request by TeddyTN**
Added headless mode for client installer

### CODE REVIEW

**Comment by TeddyTN** [comment]
Is any thing wrong with my PR?

**Comment by LexManos** [comment]
We do not support headless client install.
There is no reason you would need this.

**Comment by TeddyTN** [comment]
It's a nice feature if you like to configure your games over package managers like brew 😄

**Comment by LexManos** [comment]
If some other 3rd party wants to come in and take money out of our pockets then they can work for it.
Installing and downloading the libraries isn't hard.
Sadly this is the sole way that Forge makes money {people downloading the installer} Encouraging and facilitating people to bypass that is not something we can do.
We won't STOP people who put the effort into doing it themselves, but we will not support them doing it.
Sadly, this is business, and I need to pay rent/bills.

**Pull request closed without merging**
