### PR TITLE
Added command line options useful for mod installers that execute Forge installer.

### PR DESCRIPTION
**Pull request by linuxrules94**
I also removed a potentially unwanted edit.

### CODE REVIEW

**Comment by LexManos** [comment]
I dont see any use in this.

**Comment by linuxrules94** [comment]
Why?

**Comment by LexManos** [comment]
Because its a value in the config file in the installer.
Again, it's not for YOU to ask why its for you to ANSWER why.

**Comment by linuxrules94** [comment]
"Again, it's not for YOU to ask why its for you to ANSWER why." Hence why I have told you what it does.
No need to shout on the internet.

**Comment by LexManos** [comment]
Its not shouting its emphasizing. The entire sentence being caps would be shouting.
And you reasoning is not valid in my opinion hence the close.
Unless you have something to actually say then this is done.

**Comment by linuxrules94** [comment]
OK

**Pull request closed without merging**
