### PR TITLE
Fix some messages being logged twice and add min java version check

### PR DESCRIPTION
**Pull request by ichttt**
Adds a check to ensure that the user has a java version that can handle the let's encrypt certificates. This is still a common source of problems that people come with to the forums.
Also fixes a minor issue that would cause certain messages to be logged twice to console and file.

### CODE REVIEW

**Review by tterrag1098 — APPROVED** [review]

**Comment by LexManos** [comment]
I was more thinking we should include the letsencrypt cert like we do in Forge itself. As the java version Moajng ships is 51, which doessn't have the cert.

**Comment by ichttt** [comment]
Sure, I can do this as well

**Comment by ichttt** [comment]
Updated to include the Let's encrypt certificate, code for injeting has been taken from FMLLauncher and modified to run with installer libs

**Comment by LexManos** [comment]
```
Execution failed for task ':checkLicenseMain'.

> License violations were found: src/main/java/net/minecraftforge/installer/FixSSL.java
```

**Pull request merged**
