### PR TITLE
Print help if headless and no options present

### PR DESCRIPTION
**Pull request by XakepSDK**
Print help if headless and no options present

### CODE REVIEW

**Comment by tilda** [comment]
Build successful, however upon running it threw a NPE. Not much logging:
```java
java.net.preferIPv4Stack=true
Exception in thread "main"
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:113)
        at net.minecraftforge.installer.json.Util.loadInstallProfile(Util.java:38)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:160)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:135)
```
If there's anything extra needed let me know (this is on GUI system btw)

**Comment by tilda** [comment]
Non-GUI system (not sure why this happens, system running Debian)
```java
java.net.preferIPv4Stack=true
Exception in thread "main"
java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:154)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:135)
```

**Comment by XakepSDK** [comment]
It searches for `install_profile.json`, only test resources contain it.
I think, jenkins puts this at build time.

**Comment by tilda** [comment]
I see, I will put that in and see the results I get

**Comment by LemADEC** [comment]
I took the compiled 'fatjar', copied its content into forge-1.12.2-14.23.5.2814-installer.jar, then transferred the updated jar to our dedicated box.
When passing no arguments it does an NPE:
```
[warptech@play ~]$ java -jar forge-1.12.2-14.23.5.2814-installer.jar
java.net.preferIPv4Stack=true
Exception in thread "main"
java.lang.NullPointerException
        at sun.misc.MetaIndex.mayContain(MetaIndex.java:242)
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1044)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:302)
        at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1264)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1091)
        at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:233)
        at java.lang.Class.getResourceAsStream(Class.java:2223)
        at net.minecraftforge.installer.InstallerPanel.getImage(InstallerPanel.java:145)
        at net.minecraftforge.installer.InstallerPanel.<init>(InstallerPanel.java:170)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:161)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:135)
[warptech@play ~]$
```
This is on `CentOS Linux release 7.6.1810 (Core)` with openjdk 1.8.0_191-b12
This also fails on my Windows desktop, or just by adding the `install_profile.json` to the fatjar.
So I guess, my compilation is erroneous.

**Comment by LexManos** [comment]
from the sounds of this, everyone is saying it's broken. so unpullable.

**Pull request closed without merging**
